'use client'

import { useEffect, useRef, useState } from 'react'
import type { Map as LeafletMap, CircleMarker } from 'leaflet'
import { MapPinned, Navigation, Radio } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'
import type { TaskLiveLocationRow, TaskStatus } from '@/types/database'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'

interface Coordinate { latitude: number; longitude: number }
function distanceKm(a: Coordinate, b: Coordinate) { const r=6371; const dLat=(b.latitude-a.latitude)*Math.PI/180; const dLon=(b.longitude-a.longitude)*Math.PI/180; const x=Math.sin(dLat/2)**2+Math.cos(a.latitude*Math.PI/180)*Math.cos(b.latitude*Math.PI/180)*Math.sin(dLon/2)**2; return 2*r*Math.atan2(Math.sqrt(x),Math.sqrt(1-x)) }
function stage(status: TaskStatus) { if(status==='assigned') return ['Agent assigned','Your Go Agent is preparing to set out.']; if(status==='en_route') return ['Agent on the way','Live progress to the task location.']; if(status==='arrived') return ['Agent has arrived','The Go Agent is at the task location.']; if(status==='in_progress') return ['Task in progress','Your Go Agent is carrying out the task.']; return ['Task tracking','Location updates appear here when available.'] }

export function TaskLiveMap({ taskId, status, initialLocation, pickup, destination }: { taskId:string; status:TaskStatus; initialLocation:TaskLiveLocationRow|null; pickup?:Coordinate|null; destination?:Coordinate|null }) {
 const containerRef=useRef<HTMLDivElement>(null); const mapRef=useRef<LeafletMap|null>(null); const markerRef=useRef<CircleMarker|null>(null); const [location,setLocation]=useState(initialLocation); const [open,setOpen]=useState(false)
 useEffect(()=>setLocation(initialLocation),[initialLocation])
 useEffect(()=>{ if(!open||!containerRef.current||mapRef.current)return; let disposed=false; void import('leaflet').then(L=>{if(disposed||!containerRef.current)return; const center=initialLocation?[initialLocation.latitude,initialLocation.longitude] as [number,number]:pickup?[pickup.latitude,pickup.longitude] as [number,number]:[4.9757,8.3417] as [number,number]; const map=L.map(containerRef.current,{zoomControl:true}).setView(center,initialLocation||pickup?15:12); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap contributors',maxZoom:19}).addTo(map); if(pickup)L.circleMarker([pickup.latitude,pickup.longitude],{radius:7,color:'#0b2d6b',fillOpacity:.9}).bindTooltip('Task location').addTo(map); if(destination)L.circleMarker([destination.latitude,destination.longitude],{radius:7,color:'#f59e0b',fillOpacity:.9}).bindTooltip('Destination').addTo(map); if(initialLocation)markerRef.current=L.circleMarker([initialLocation.latitude,initialLocation.longitude],{radius:9,color:'#fff',weight:3,fillColor:'#007bff',fillOpacity:1}).bindTooltip('Go Agent').addTo(map); mapRef.current=map; setTimeout(()=>map.invalidateSize(),50)}); return()=>{disposed=true;mapRef.current?.remove();mapRef.current=null;markerRef.current=null}},[open,initialLocation,pickup,destination])
 useEffect(()=>{if(!location||!mapRef.current)return; void import('leaflet').then(L=>{const point:[number,number]=[location.latitude,location.longitude]; if(markerRef.current)markerRef.current.setLatLng(point); else markerRef.current=L.circleMarker(point,{radius:9,color:'#fff',weight:3,fillColor:'#007bff',fillOpacity:1}).bindTooltip('Go Agent').addTo(mapRef.current!); mapRef.current?.panTo(point)})},[location])
 useEffect(()=>{const supabase=createClient(); const channel=supabase.channel(`task-location:${taskId}`).on('postgres_changes',{event:'*',schema:'public',table:'task_live_locations',filter:`task_id=eq.${taskId}`},payload=>{if(payload.eventType!=='DELETE')setLocation(payload.new as TaskLiveLocationRow)}).subscribe(); return()=>{void supabase.removeChannel(channel)}},[taskId])
 const [title,description]=stage(status); const active=Boolean(location?.is_tracking&&['en_route','arrived','in_progress'].includes(status)); const remaining=location&&pickup&&status==='en_route'?distanceKm(location,pickup):null
 return <Dialog open={open} onOpenChange={setOpen}><div className="rounded-2xl border bg-card p-4 shadow-sm sm:p-5"><div className="flex items-start gap-3"><span className="rounded-xl bg-primary-subtle p-2.5 text-primary"><Navigation className="h-5 w-5" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{title}</p>{active?<span className="inline-flex items-center gap-1 rounded-full bg-success-subtle px-2 py-1 text-[10px] font-bold uppercase tracking-wide text-success"><Radio className="h-3 w-3" />Live</span>:null}</div><p className="mt-1 text-sm text-muted-foreground">{description}</p></div></div><div className="mt-4 grid grid-cols-2 gap-2 rounded-xl bg-muted/60 p-3 text-sm"><div><p className="text-xs text-muted-foreground">Distance remaining</p><p className="mt-1 font-semibold">{remaining!=null?`${remaining.toFixed(1)} km`:'Updates when available'}</p></div><div><p className="text-xs text-muted-foreground">ETA</p><p className="mt-1 font-semibold">Live route required</p></div></div><DialogTrigger asChild><Button variant="outline" className="mt-4 w-full"><MapPinned className="h-4 w-4" />Open live map</Button></DialogTrigger></div><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>Live Go Agent position and task locations. Distance shown on the card is straight-line distance, not a road-route ETA.</DialogDescription></DialogHeader><div ref={containerRef} className="h-[min(62dvh,32rem)] overflow-hidden rounded-xl border bg-muted" aria-label="Live task map" /><div className="flex justify-between gap-3 text-xs text-muted-foreground"><span>{active?'Live location updating automatically':location?'Last shared Go Agent location':'Tracking has not started yet'}</span>{location?<span>{new Date(location.recorded_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span>:null}</div></DialogContent></Dialog>
}
